### ISSUE TITLE
Label isn't centered - Frame is ugly

### ISSUE THREAD

**Issue by Jaxswat** [Cuniq/SkypeBot#3]
Label isn't centered on the JFrame. I fixed a lot of code, but can't make a Pull request :/

In Main.java where you define the JLabel:

```
private static JLabel label = new JLabel("Skype Bot is running.", SwingConstants.CENTER);
```

As you can guess, this keeps the label in the center of the JFrame.

On to the next problem, the frame is ugly, I shaped it to fit the label and stopped it from re-sizing.

In Main.java where you set up the frame:

```
    frame.setSize(200, 100);
    frame.setResizable(false);
```

**Comment by Cuniq** [comment]
Wow! Thks for the fixes! That's really nice. Sorry for the pull requests but i am really new to github should make something to open them?

**Comment by Cuniq** [comment]
You can send me the code if you like and i will add it

**Comment by Jaxswat** [comment]
I figured it out. All I need to do is fork the repository and then proceed to make pull requests.
